### ISSUE TITLE
QMK (Vial) source code pointing to wrong location

### ISSUE THREAD

**Issue by dhruvinsh** [dcpedit/pillzmod#10]
Hi @dcpedit 
As mentioned, the QMK firmware source code is missing. If you can point me to correct location that would be great. :)

**Comment by dhruvinsh** [comment]
I think I found it, it was on different branch. 
https://github.com/vial-kb/vial-qmk/compare/vial...dcpedit:vial-qmk:pillzmod

if that is the case, document (README.md) file need an update :)

**Comment by dcpedit** [comment]
Thanks for pointing that out. Readme updated
