### ISSUE TITLE
Best controller to use?

### ISSUE THREAD

**Issue by pinpox** [dcpedit/pillzmod#14]
Hello,
sorry for asking here but I couldn't find any other contact information. I'm planning to build this for a kinesis Essential contoured keyboard, of all the controllers supported which one is the best or the one you would recommend? 

I want build the "Pro" version with Bluetooth, does it also support wired mode (I need both Bluetooth AND wired options if possible)

**Comment by a10kiloham** [comment]
The nicenano is the most versatile. You can use it wired or wireless
