### ISSUE TITLE
Ported build to use ZMK GitHub actions

### ISSUE THREAD

**Issue by keepitsimplejim** [dcpedit/pillzmod#8]
I'm looking into upgrading my stock keyboard to ZMK (thanks to your repo) and I've been reading through the docs and I've created the following ZMK firmware build using GitHub actions and thought that you might be interested.

https://github.com/keepitsimplejim/zmk-config-pillzmod-kinesis-adv

**Comment by dcpedit** [comment]
Awesome!  Thanks for sharing this.  I'll add it to the readme
